<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

require_once 'Sabai/Model/EntityCollection/Decorator/DescendantEntitiesCount.php';

class Xigg_Model_CategoriesWithDescendantsCountBase extends Sabai_Model_EntityCollection_Decorator_DescendantEntitiesCount
{
    function Xigg_Model_CategoriesWithDescendantsCountBase(&$collection)
    {
        parent::Sabai_Model_EntityCollection_Decorator_DescendantEntitiesCount('Category', $collection);
    }
}