<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
Xigg/library/Xigg/Model/CategoryForm.php
*/
class Xigg_Model_CategoryFormBase extends Sabai_Model_EntityForm
{
    function onInit($params)
    {
        require_once 'Sabai/Form/Element/InputText.php';
        $this->addElement(new Sabai_Form_Element_InputText('name', 80, 255), _('Name'));
        require_once 'Sabai/Form/Element/Textarea.php';
        $this->addElement(new Sabai_Form_Element_Textarea('description', 10, 70), _('Description'));
        require_once 'Sabai/Form/Element/SelectTreeEntity.php';
        $element =& new Sabai_Form_Element_SelectTreeEntity($this->_model, 'Category', 'Parent', 1, ' - ');
        $this->addElement($element, _('Parent category'));
        $this->_onInit($params);
    }

    function onEntity(&$entity)
    {
        if ($this->hasElement('name')) {
            $this->setValueFor('name', $entity->getVar('name'));
        }
        if ($this->hasElement('description')) {
            $this->setValueFor('description', $entity->getVar('description'));
        }
        if ($this->hasElement('Parent')) {
            $this->setValueFor('Parent', $entity->getVar('parent'));
        }
        $this->_onEntity($entity);
    }

    function onFillEntity(&$entity)
    {
        $vars = array();
        foreach (array('name' => 'name', 'description' => 'description', 'parent' => 'Parent') as $var_name => $form_name) {
            if ($this->hasElement($form_name)) {
                $vars[$var_name] = $this->getValueFor($form_name);
            }
        }
        $entity->setVars($vars);
        $this->_onFillEntity($entity);
    }

    function _onInit($params){}
    function _onEntity(&$entity){}
    function _onFillEntity(&$entity){}
}