<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
Xigg/library/Xigg/Model/CategoryCriteria.php
*/
require_once 'Sabai/Model/EntityCriteria.php';

class Xigg_Model_CategoryCriteriaBase extends Sabai_Model_EntityCriteria
{

    function &idIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('category_id', $value));
    }

    function &idIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('category_id', $value, '>'));
    }

    function &idIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('category_id', $value, '<'));
    }

    function &idIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('category_id', $value, '>='));
    }

    function &idIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('category_id', $value, '<='));
    }

    function &idIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('category_id', $values));
    }

    function &idNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('category_id', $values));
    }

    function &createdIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('category_created', $value));
    }

    function &createdIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('category_created', $value, '>'));
    }

    function &createdIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('category_created', $value, '<'));
    }

    function &createdIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('category_created', $value, '>='));
    }

    function &createdIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('category_created', $value, '<='));
    }

    function &createdIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('category_created', $values));
    }

    function &createdNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('category_created', $values));
    }

    function &updatedIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('category_updated', $value));
    }

    function &updatedIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('category_updated', $value, '>'));
    }

    function &updatedIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('category_updated', $value, '<'));
    }

    function &updatedIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('category_updated', $value, '>='));
    }

    function &updatedIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('category_updated', $value, '<='));
    }

    function &updatedIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('category_updated', $values));
    }

    function &updatedNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('category_updated', $values));
    }

    function &nameIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('category_name', $value));
    }

    function &nameStartsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('category_name', $str, '^'));
    }

    function &nameEndsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('category_name', $str, '$'));
    }

    function &nameContains($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('category_name', $str));
    }

    function &nameIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('category_name', $values));
    }

    function &nameNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('category_name', $values));
    }

    function &descriptionStartsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('category_description', $str, '^'));
    }

    function &descriptionEndsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('category_description', $str, '$'));
    }

    function &descriptionContains($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('category_description', $str));
    }

    function &parentIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('category_parent', $value));
    }

    function &parentIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('category_parent', $value, '>'));
    }

    function &parentIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('category_parent', $value, '<'));
    }

    function &parentIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('category_parent', $value, '>='));
    }

    function &parentIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('category_parent', $value, '<='));
    }

    function &parentIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('category_parent', $values));
    }

    function &parentNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('category_parent', $values));
    }

    function &node_countIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('category_node_count', $value));
    }

    function &node_countIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('category_node_count', $value, '>'));
    }

    function &node_countIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('category_node_count', $value, '<'));
    }

    function &node_countIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('category_node_count', $value, '>='));
    }

    function &node_countIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('category_node_count', $value, '<='));
    }

    function &node_countIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('category_node_count', $values));
    }

    function &node_countNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('category_node_count', $values));
    }

    function &node_lastIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('category_node_last', $value));
    }

    function &node_lastIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('category_node_last', $value, '>'));
    }

    function &node_lastIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('category_node_last', $value, '<'));
    }

    function &node_lastIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('category_node_last', $value, '>='));
    }

    function &node_lastIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('category_node_last', $value, '<='));
    }

    function &node_lastIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('category_node_last', $values));
    }

    function &node_lastNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('category_node_last', $values));
    }

    function &node_lasttimeIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('category_node_lasttime', $value));
    }

    function &node_lasttimeIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('category_node_lasttime', $value, '>'));
    }

    function &node_lasttimeIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('category_node_lasttime', $value, '<'));
    }

    function &node_lasttimeIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('category_node_lasttime', $value, '>='));
    }

    function &node_lasttimeIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('category_node_lasttime', $value, '<='));
    }

    function &node_lasttimeIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('category_node_lasttime', $values));
    }

    function &node_lasttimeNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('category_node_lasttime', $values));
    }
}