<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

require_once 'Sabai/Model/EntityCollection/Decorator/ForeignEntities.php';

class Xigg_Model_CategoriesWithNodesBase extends Sabai_Model_EntityCollection_Decorator_ForeignEntities
{
    function Xigg_Model_CategoriesWithNodesBase(&$collection)
    {
        parent::Sabai_Model_EntityCollection_Decorator_ForeignEntities('node_category_id', 'Node', 'node_category_id', $collection);
    }
}