<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

require_once 'Sabai/Model/EntityCollection/Decorator/ParentEntitiesCount.php';

class Xigg_Model_CategoriesWithParentsCountBase extends Sabai_Model_EntityCollection_Decorator_ParentEntitiesCount
{
    function Xigg_Model_CategoriesWithParentsCountBase(&$collection)
    {
        parent::Sabai_Model_EntityCollection_Decorator_ParentEntitiesCount('Category', $collection);
    }
}