<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

require_once 'Sabai/Model/EntityCollection/Decorator/ChildEntities.php';

class Xigg_Model_CommentsWithChildrenBase extends Sabai_Model_EntityCollection_Decorator_ChildEntities
{
    function Xigg_Model_CommentsWithChildrenBase(&$collection)
    {
        parent::Sabai_Model_EntityCollection_Decorator_ChildEntities('Comment', 'comment_parent', $collection);
    }
}