<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
Xigg/library/Xigg/Model/CommentCriteria.php
*/
require_once 'Sabai/Model/EntityCriteria.php';

class Xigg_Model_CommentCriteriaBase extends Sabai_Model_EntityCriteria
{

    function &idIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('comment_id', $value));
    }

    function &idIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('comment_id', $value, '>'));
    }

    function &idIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('comment_id', $value, '<'));
    }

    function &idIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('comment_id', $value, '>='));
    }

    function &idIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('comment_id', $value, '<='));
    }

    function &idIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('comment_id', $values));
    }

    function &idNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('comment_id', $values));
    }

    function &createdIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('comment_created', $value));
    }

    function &createdIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('comment_created', $value, '>'));
    }

    function &createdIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('comment_created', $value, '<'));
    }

    function &createdIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('comment_created', $value, '>='));
    }

    function &createdIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('comment_created', $value, '<='));
    }

    function &createdIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('comment_created', $values));
    }

    function &createdNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('comment_created', $values));
    }

    function &updatedIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('comment_updated', $value));
    }

    function &updatedIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('comment_updated', $value, '>'));
    }

    function &updatedIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('comment_updated', $value, '<'));
    }

    function &updatedIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('comment_updated', $value, '>='));
    }

    function &updatedIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('comment_updated', $value, '<='));
    }

    function &updatedIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('comment_updated', $values));
    }

    function &updatedNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('comment_updated', $values));
    }

    function &titleIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('comment_title', $value));
    }

    function &titleStartsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('comment_title', $str, '^'));
    }

    function &titleEndsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('comment_title', $str, '$'));
    }

    function &titleContains($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('comment_title', $str));
    }

    function &titleIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('comment_title', $values));
    }

    function &titleNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('comment_title', $values));
    }

    function &content_syntaxIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('comment_content_syntax', $value));
    }

    function &content_syntaxStartsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('comment_content_syntax', $str, '^'));
    }

    function &content_syntaxEndsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('comment_content_syntax', $str, '$'));
    }

    function &content_syntaxContains($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('comment_content_syntax', $str));
    }

    function &content_syntaxIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('comment_content_syntax', $values));
    }

    function &content_syntaxNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('comment_content_syntax', $values));
    }

    function &bodyStartsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('comment_body', $str, '^'));
    }

    function &bodyEndsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('comment_body', $str, '$'));
    }

    function &bodyContains($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('comment_body', $str));
    }

    function &body_htmlStartsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('comment_body_html', $str, '^'));
    }

    function &body_htmlEndsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('comment_body_html', $str, '$'));
    }

    function &body_htmlContains($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('comment_body_html', $str));
    }

    function &allow_editIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('comment_allow_edit', $value));
    }

    function &allow_editIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('comment_allow_edit', $value, '>'));
    }

    function &allow_editIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('comment_allow_edit', $value, '<'));
    }

    function &allow_editIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('comment_allow_edit', $value, '>='));
    }

    function &allow_editIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('comment_allow_edit', $value, '<='));
    }

    function &allow_editIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('comment_allow_edit', $values));
    }

    function &allow_editNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('comment_allow_edit', $values));
    }

    function &node_idIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('comment_node_id', $value));
    }

    function &node_idIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('comment_node_id', $value, '>'));
    }

    function &node_idIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('comment_node_id', $value, '<'));
    }

    function &node_idIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('comment_node_id', $value, '>='));
    }

    function &node_idIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('comment_node_id', $value, '<='));
    }

    function &node_idIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('comment_node_id', $values));
    }

    function &node_idNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('comment_node_id', $values));
    }

    function &parentIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('comment_parent', $value));
    }

    function &parentIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('comment_parent', $value, '>'));
    }

    function &parentIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('comment_parent', $value, '<'));
    }

    function &parentIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('comment_parent', $value, '>='));
    }

    function &parentIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('comment_parent', $value, '<='));
    }

    function &parentIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('comment_parent', $values));
    }

    function &parentNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('comment_parent', $values));
    }

    function &useridIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('comment_userid', $value));
    }

    function &useridStartsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('comment_userid', $str, '^'));
    }

    function &useridEndsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('comment_userid', $str, '$'));
    }

    function &useridContains($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('comment_userid', $str));
    }

    function &useridIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('comment_userid', $values));
    }

    function &useridNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('comment_userid', $values));
    }
}