<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
Xigg/library/Xigg/Model/MemberGateway.php
*/
class Xigg_Model_MemberGatewayBase extends Sabai_Model_Gateway
{
    function getName()
    {
        return 'member';
    }

    function getFields()
    {
        return array('member_id' => SABAI_MODEL_KEY_TYPE_INT, 'member_created' => SABAI_MODEL_KEY_TYPE_INT, 'member_updated' => SABAI_MODEL_KEY_TYPE_INT, 'member_role_id' => SABAI_MODEL_KEY_TYPE_INT_NULL, 'member_userid' => SABAI_MODEL_KEY_TYPE_VARCHAR);
    }

    function _getSelectByIdQuery($id, $fields)
    {
        $fields = empty($fields) ? '*' : implode(', t.', $fields);
        return sprintf('SELECT t.%s FROM %smember t WHERE member_id = %d', $fields, $this->_db->getResourcePrefix(), $id);
    }

    function _getSelectByCriteriaQuery($criteriaStr, $fields)
    {
        $fields = empty($fields) ? '*' : implode(', t.', $fields);
        return sprintf('SELECT t.%1$s FROM %2$smember t WHERE %3$s', $fields, $this->_db->getResourcePrefix(), $criteriaStr);
    }

    function _getInsertQuery($values)
    {
        $values['member_created'] = time();
        $values['member_updated'] = 0;
        $values['member_role_id'] = !empty($values['member_role_id']) ? intval($values['member_role_id']) : 'NULL';
        return sprintf("INSERT INTO %smember(member_created, member_updated, member_role_id, member_userid) VALUES(%d, %d, %s, %s)", $this->_db->getResourcePrefix(), $values['member_created'], $values['member_updated'], $values['member_role_id'], $this->_db->escapeString($values['member_userid']));
    }

    function _getUpdateQuery($id, $values)
    {
        $values['member_role_id'] = !empty($values['member_role_id']) ? intval($values['member_role_id']) : 'NULL';
        $last_update = $values['member_updated'];
        $values['member_updated'] = time();
        return sprintf("UPDATE %smember SET member_updated = %d, member_role_id = %s, member_userid = %s WHERE member_id = %d AND member_updated = %d", $this->_db->getResourcePrefix(), $values['member_updated'], $values['member_role_id'], $this->_db->escapeString($values['member_userid']), $id, $last_update);
    }

    function _getDeleteQuery($id)
    {
        return sprintf('DELETE FROM %1$smember WHERE member_id = %2$d', $this->_db->getResourcePrefix(), $id);
    }

    function _getUpdateByCriteriaQuery($criteriaStr, $sets)
    {
        $sets['member_updated'] = 'member_updated=' . time();
        return sprintf('UPDATE %smember SET %s WHERE %s', $this->_db->getResourcePrefix(), implode(',', $sets), $criteriaStr);
    }

    function _getDeleteByCriteriaQuery($criteriaStr)
    {
        return sprintf('DELETE FROM %1$smember WHERE %2$s', $this->_db->getResourcePrefix(), $criteriaStr);
    }

    function _getCountByCriteriaQuery($criteriaStr)
    {
        return sprintf('SELECT COUNT(*) FROM %1$smember WHERE %2$s', $this->_db->getResourcePrefix(), $criteriaStr);
    }

    function _afterInsertTrigger1($id, $new)
    {
        if (!empty($new['member_role_id'])) {
            $this->_db->exec(sprintf('UPDATE %srole SET role_member_count = role_member_count + 1, role_member_last = %d, role_member_lasttime = %d WHERE role_id = %d', $this->_db->getResourcePrefix(), $id, $new['member_created'], $new['member_role_id']));
        }
    }

    function _afterDeleteTrigger1($id, $old)
    {
        if (!empty($old['member_role_id'])) {
            $sql = sprintf('SELECT member_id, member_created FROM %smember WHERE member_role_id = %d ORDER BY member_created DESC', $this->_db->getResourcePrefix(), $old['member_role_id']);
            if (($rs =& $this->_db->query($sql, 1, 0)) && ($rs->rowCount() > 0)) {
                $row = $rs->fetchAssoc();
                $this->_db->exec(sprintf('UPDATE %srole SET role_member_count = role_member_count - 1, role_member_last = %d, role_member_lasttime = %d WHERE role_id = %d', $this->_db->getResourcePrefix(), $row['member_id'], $row['member_created'], $old['member_role_id']));
            } else {
                $this->_db->exec(sprintf('UPDATE %srole SET role_member_count = role_member_count - 1, role_member_last = 0, role_member_lasttime = role_created WHERE role_id = %d', $this->_db->getResourcePrefix(), $old['member_role_id']));
            }
        }
    }

    function _afterUpdateTrigger1($id, $new, $old)
    {
        if (empty($old['member_role_id']) && !empty($new['member_role_id'])) {
            $this->_db->exec(sprintf('UPDATE %srole SET role_member_count = role_member_count + 1, role_member_last = %d, role_member_lasttime = %d WHERE role_id = %d', $this->_db->getResourcePrefix(), $id, $new['member_created'], $new['member_role_id']));
        } elseif (!empty($old['member_role_id']) && empty($new['member_role_id'])) {
            $sql = sprintf('SELECT member_id, member_created FROM %smember WHERE member_role_id = %d ORDER BY member_created DESC', $this->_db->getResourcePrefix(), $old['member_role_id']);
            if (($rs =& $this->_db->query($sql, 1, 0)) && ($rs->rowCount() > 0)) {
                $row = $rs->fetchAssoc();
                $this->_db->exec(sprintf('UPDATE %srole SET role_member_count = role_member_count - 1, role_member_last = %d, role_member_lasttime = %d WHERE role_id = %d', $this->_db->getResourcePrefix(), $row['member_id'], $row['member_created'], $old['member_role_id']));
            } else {
                $this->_db->exec(sprintf('UPDATE %srole SET role_member_count = role_member_count - 1, role_member_last = 0, role_member_lasttime = role_created WHERE role_id = %d', $this->_db->getResourcePrefix(), $old['member_role_id']));
            }
        } elseif ($old['member_role_id'] != $new['member_role_id']) {
            $sql = sprintf('SELECT member_id, member_created FROM %smember WHERE member_role_id = %d ORDER BY member_created DESC', $this->_db->getResourcePrefix(), $old['member_role_id']);
            if (($rs =& $this->_db->query($sql, 1, 0)) && ($rs->rowCount() > 0)) {
                $row = $rs->fetchAssoc();
                $this->_db->exec(sprintf('UPDATE %srole SET role_member_count = role_member_count - 1, role_member_last = %d, role_member_lasttime = %d WHERE role_id = %d', $this->_db->getResourcePrefix(), $row['member_id'], $row['member_created'], $old['member_role_id']));
            } else {
                $this->_db->exec(sprintf('UPDATE %srole SET role_member_count = role_member_count - 1, role_member_last = 0, role_member_lasttime = role_created WHERE role_id = %d', $this->_db->getResourcePrefix(), $old['member_role_id']));
            }
            $this->_db->exec(sprintf('UPDATE %srole SET role_member_count = role_member_count + 1, role_member_last = %d, role_member_lasttime = %d WHERE role_id = %d', $this->_db->getResourcePrefix(), $id, $new['member_created'], $new['member_role_id']));
        }
    }

    function _afterInsertTrigger($id, $new)
    {
        $this->_afterInsertTrigger1($id, $new);
    }

    function _afterUpdateTrigger($id, $new, $old)
    {
        $this->_afterUpdateTrigger1($id, $new, $old);
    }

    function _afterDeleteTrigger($id, $old)
    {
        $this->_afterDeleteTrigger1($id, $old);
    }
}