<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

require_once 'Sabai/Model/EntityCollection/Decorator/AssocEntities.php';

class Xigg_Model_NodesWithTagsBase extends Sabai_Model_EntityCollection_Decorator_AssocEntities
{
    function Xigg_Model_NodesWithTagsBase(&$collection)
    {
        parent::Sabai_Model_EntityCollection_Decorator_AssocEntities('Node2tag', 'node2tag_node_id', 'tag', 'Tag', $collection);
    }
}