<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

require_once 'Sabai/Model/EntityCollection/Decorator/ForeignEntities.php';

class Xigg_Model_NodesWithCommentsBase extends Sabai_Model_EntityCollection_Decorator_ForeignEntities
{
    function Xigg_Model_NodesWithCommentsBase(&$collection)
    {
        parent::Sabai_Model_EntityCollection_Decorator_ForeignEntities('comment_node_id', 'Comment', 'comment_node_id', $collection);
    }
}