<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

require_once 'Sabai/Model/EntityCollection/Decorator/ForeignEntities.php';

class Xigg_Model_NodesWithTrackbacksBase extends Sabai_Model_EntityCollection_Decorator_ForeignEntities
{
    function Xigg_Model_NodesWithTrackbacksBase(&$collection)
    {
        parent::Sabai_Model_EntityCollection_Decorator_ForeignEntities('trackback_node_id', 'Trackback', 'trackback_node_id', $collection);
    }
}