<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
Xigg/library/Xigg/Model/Node2tagGateway.php
*/
class Xigg_Model_Node2tagGatewayBase extends Sabai_Model_Gateway
{
    function getName()
    {
        return 'node2tag';
    }

    function getFields()
    {
        return array('node2tag_id' => SABAI_MODEL_KEY_TYPE_INT, 'node2tag_created' => SABAI_MODEL_KEY_TYPE_INT, 'node2tag_updated' => SABAI_MODEL_KEY_TYPE_INT, 'node2tag_node_id' => SABAI_MODEL_KEY_TYPE_INT_NULL, 'node2tag_tag_id' => SABAI_MODEL_KEY_TYPE_INT_NULL);
    }

    function getSortFields()
    {
        return array('node_id' => SABAI_MODEL_KEY_TYPE_INT, 'node_created' => SABAI_MODEL_KEY_TYPE_INT, 'node_updated' => SABAI_MODEL_KEY_TYPE_INT, 'node_title' => SABAI_MODEL_KEY_TYPE_VARCHAR, 'node_source' => SABAI_MODEL_KEY_TYPE_VARCHAR, 'node_source_title' => SABAI_MODEL_KEY_TYPE_VARCHAR, 'node_content_syntax' => SABAI_MODEL_KEY_TYPE_VARCHAR, 'node_body' => SABAI_MODEL_KEY_TYPE_TEXT, 'node_body_html' => SABAI_MODEL_KEY_TYPE_TEXT, 'node_teaser' => SABAI_MODEL_KEY_TYPE_TEXT, 'node_teaser_html' => SABAI_MODEL_KEY_TYPE_TEXT, 'node_published' => SABAI_MODEL_KEY_TYPE_INT, 'node_allow_comments' => SABAI_MODEL_KEY_TYPE_INT, 'node_allow_trackbacks' => SABAI_MODEL_KEY_TYPE_INT, 'node_allow_edit' => SABAI_MODEL_KEY_TYPE_INT, 'node_status' => SABAI_MODEL_KEY_TYPE_INT, 'node_hidden' => SABAI_MODEL_KEY_TYPE_INT, 'node_priority' => SABAI_MODEL_KEY_TYPE_INT, 'node_views' => SABAI_MODEL_KEY_TYPE_INT, 'node_category_id' => SABAI_MODEL_KEY_TYPE_INT_NULL, 'node_userid' => SABAI_MODEL_KEY_TYPE_VARCHAR, 'node_comment_count' => SABAI_MODEL_KEY_TYPE_INT, 'node_comment_last' => SABAI_MODEL_KEY_TYPE_INT, 'node_comment_lasttime' => SABAI_MODEL_KEY_TYPE_INT, 'node_trackback_count' => SABAI_MODEL_KEY_TYPE_INT, 'node_trackback_last' => SABAI_MODEL_KEY_TYPE_INT, 'node_trackback_lasttime' => SABAI_MODEL_KEY_TYPE_INT, 'node_vote_count' => SABAI_MODEL_KEY_TYPE_INT, 'node_vote_last' => SABAI_MODEL_KEY_TYPE_INT, 'node_vote_lasttime' => SABAI_MODEL_KEY_TYPE_INT, 'node_view_count' => SABAI_MODEL_KEY_TYPE_INT, 'node_view_last' => SABAI_MODEL_KEY_TYPE_INT, 'node_view_lasttime' => SABAI_MODEL_KEY_TYPE_INT, 'tag_id' => SABAI_MODEL_KEY_TYPE_INT, 'tag_created' => SABAI_MODEL_KEY_TYPE_INT, 'tag_updated' => SABAI_MODEL_KEY_TYPE_INT, 'tag_name' => SABAI_MODEL_KEY_TYPE_VARCHAR);
    }

    function _getSelectByIdQuery($id, $fields)
    {
        $fields = empty($fields) ? 'node2tag.*, node.*, tag.*' : implode(', ', $fields);
        return sprintf('SELECT %2$s FROM %1$snode2tag node2tag INNER JOIN %1$snode node ON node.node_id = node2tag.node2tag_node_id INNER JOIN %1$stag tag ON tag.tag_id = node2tag.node2tag_tag_id WHERE node2tag.node2tag_id = %3$d', $this->_db->getResourcePrefix(), $fields, $id);
    }

    function _getSelectByCriteriaQuery($criteriaStr, $fields)
    {
        $fields = empty($fields) ? 'node2tag.*, node.*, tag.*' : implode(', ', $fields);
        return sprintf('SELECT %2$s FROM %1$snode2tag node2tag INNER JOIN %1$snode node ON node.node_id = node2tag.node2tag_node_id INNER JOIN %1$stag tag ON tag.tag_id = node2tag.node2tag_tag_id WHERE %3$s', $this->_db->getResourcePrefix(), $fields, $criteriaStr);
    }

    function _getInsertQuery($values)
    {
        $values['node2tag_created'] = time();
        $values['node2tag_updated'] = 0;
        $values['node2tag_node_id'] = !empty($values['node2tag_node_id']) ? intval($values['node2tag_node_id']) : 'NULL';
        $values['node2tag_tag_id'] = !empty($values['node2tag_tag_id']) ? intval($values['node2tag_tag_id']) : 'NULL';
        return sprintf("INSERT INTO %snode2tag(node2tag_created, node2tag_updated, node2tag_node_id, node2tag_tag_id) VALUES(%d, %d, %s, %s)", $this->_db->getResourcePrefix(), $values['node2tag_created'], $values['node2tag_updated'], $values['node2tag_node_id'], $values['node2tag_tag_id']);
    }

    function _getUpdateQuery($id, $values)
    {
        $values['node2tag_node_id'] = !empty($values['node2tag_node_id']) ? intval($values['node2tag_node_id']) : 'NULL';
        $values['node2tag_tag_id'] = !empty($values['node2tag_tag_id']) ? intval($values['node2tag_tag_id']) : 'NULL';
        $last_update = $values['node2tag_updated'];
        $values['node2tag_updated'] = time();
        return sprintf("UPDATE %snode2tag SET node2tag_updated = %d, node2tag_node_id = %s, node2tag_tag_id = %s WHERE node2tag_id = %d AND node2tag_updated = %d", $this->_db->getResourcePrefix(), $values['node2tag_updated'], $values['node2tag_node_id'], $values['node2tag_tag_id'], $id, $last_update);
    }

    function _getDeleteQuery($id)
    {
        return sprintf('DELETE FROM %1$snode2tag WHERE node2tag_id = %2$d', $this->_db->getResourcePrefix(), $id);
    }

    function _getUpdateByCriteriaQuery($criteriaStr, $sets)
    {
        $sets['node2tag_updated'] = 'node2tag_updated=' . time();
        return sprintf('UPDATE %snode2tag SET %s WHERE %s', $this->_db->getResourcePrefix(), implode(',', $sets), $criteriaStr);
    }

    function _getDeleteByCriteriaQuery($criteriaStr)
    {
        return sprintf('DELETE FROM %1$snode2tag WHERE %2$s', $this->_db->getResourcePrefix(), $criteriaStr);
    }

    function _getCountByCriteriaQuery($criteriaStr)
    {
        return sprintf('SELECT COUNT(*) FROM %1$snode2tag node2tag INNER JOIN %1$snode node ON node.node_id = node2tag.node2tag_node_id INNER JOIN %1$stag tag ON tag.tag_id = node2tag.node2tag_tag_id WHERE %2$s', $this->_db->getResourcePrefix(), $criteriaStr);
    }

    function _afterInsertTrigger1($id, $new)
    {
    }

    function _afterDeleteTrigger1($id, $old)
    {
    }

    function _afterUpdateTrigger1($id, $new, $old)
    {
    }

    function _afterInsertTrigger($id, $new)
    {
        $this->_afterInsertTrigger1($id, $new);
    }

    function _afterUpdateTrigger($id, $new, $old)
    {
        $this->_afterUpdateTrigger1($id, $new, $old);
    }

    function _afterDeleteTrigger($id, $old)
    {
        $this->_afterDeleteTrigger1($id, $old);
    }
}