<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
Xigg/library/Xigg/Model/Node2tagCriteria.php
*/
require_once 'Sabai/Model/EntityCriteria.php';

class Xigg_Model_Node2tagCriteriaBase extends Sabai_Model_EntityCriteria
{

    function &idIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node2tag_id', $value));
    }

    function &idIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node2tag_id', $value, '>'));
    }

    function &idIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node2tag_id', $value, '<'));
    }

    function &idIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node2tag_id', $value, '>='));
    }

    function &idIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node2tag_id', $value, '<='));
    }

    function &idIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('node2tag_id', $values));
    }

    function &idNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('node2tag_id', $values));
    }

    function &createdIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node2tag_created', $value));
    }

    function &createdIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node2tag_created', $value, '>'));
    }

    function &createdIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node2tag_created', $value, '<'));
    }

    function &createdIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node2tag_created', $value, '>='));
    }

    function &createdIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node2tag_created', $value, '<='));
    }

    function &createdIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('node2tag_created', $values));
    }

    function &createdNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('node2tag_created', $values));
    }

    function &updatedIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node2tag_updated', $value));
    }

    function &updatedIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node2tag_updated', $value, '>'));
    }

    function &updatedIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node2tag_updated', $value, '<'));
    }

    function &updatedIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node2tag_updated', $value, '>='));
    }

    function &updatedIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node2tag_updated', $value, '<='));
    }

    function &updatedIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('node2tag_updated', $values));
    }

    function &updatedNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('node2tag_updated', $values));
    }

    function &node_idIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node2tag_node_id', $value));
    }

    function &node_idIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node2tag_node_id', $value, '>'));
    }

    function &node_idIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node2tag_node_id', $value, '<'));
    }

    function &node_idIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node2tag_node_id', $value, '>='));
    }

    function &node_idIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node2tag_node_id', $value, '<='));
    }

    function &node_idIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('node2tag_node_id', $values));
    }

    function &node_idNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('node2tag_node_id', $values));
    }

    function &tag_idIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node2tag_tag_id', $value));
    }

    function &tag_idIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node2tag_tag_id', $value, '>'));
    }

    function &tag_idIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node2tag_tag_id', $value, '<'));
    }

    function &tag_idIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node2tag_tag_id', $value, '>='));
    }

    function &tag_idIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node2tag_tag_id', $value, '<='));
    }

    function &tag_idIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('node2tag_tag_id', $values));
    }

    function &tag_idNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('node2tag_tag_id', $values));
    }
}