<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

require_once 'Sabai/Model/EntityCollection/Decorator/ForeignEntitiesLast.php';

class Xigg_Model_NodesWithLastVoteBase extends Sabai_Model_EntityCollection_Decorator_ForeignEntitiesLast
{
    function Xigg_Model_NodesWithLastVoteBase(&$collection)
    {
        parent::Sabai_Model_EntityCollection_Decorator_ForeignEntitiesLast('vote_last', 'Vote', 'vote_id', $collection);
    }
}