<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
Xigg/library/Xigg/Model/NodeCriteria.php
*/
require_once 'Sabai/Model/EntityCriteria.php';

class Xigg_Model_NodeCriteriaBase extends Sabai_Model_EntityCriteria
{

    function &idIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_id', $value));
    }

    function &idIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_id', $value, '>'));
    }

    function &idIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_id', $value, '<'));
    }

    function &idIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_id', $value, '>='));
    }

    function &idIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_id', $value, '<='));
    }

    function &idIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('node_id', $values));
    }

    function &idNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('node_id', $values));
    }

    function &createdIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_created', $value));
    }

    function &createdIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_created', $value, '>'));
    }

    function &createdIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_created', $value, '<'));
    }

    function &createdIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_created', $value, '>='));
    }

    function &createdIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_created', $value, '<='));
    }

    function &createdIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('node_created', $values));
    }

    function &createdNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('node_created', $values));
    }

    function &updatedIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_updated', $value));
    }

    function &updatedIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_updated', $value, '>'));
    }

    function &updatedIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_updated', $value, '<'));
    }

    function &updatedIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_updated', $value, '>='));
    }

    function &updatedIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_updated', $value, '<='));
    }

    function &updatedIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('node_updated', $values));
    }

    function &updatedNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('node_updated', $values));
    }

    function &titleIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_title', $value));
    }

    function &titleStartsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('node_title', $str, '^'));
    }

    function &titleEndsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('node_title', $str, '$'));
    }

    function &titleContains($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('node_title', $str));
    }

    function &titleIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('node_title', $values));
    }

    function &titleNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('node_title', $values));
    }

    function &sourceIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_source', $value));
    }

    function &sourceStartsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('node_source', $str, '^'));
    }

    function &sourceEndsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('node_source', $str, '$'));
    }

    function &sourceContains($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('node_source', $str));
    }

    function &sourceIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('node_source', $values));
    }

    function &sourceNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('node_source', $values));
    }

    function &source_titleIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_source_title', $value));
    }

    function &source_titleStartsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('node_source_title', $str, '^'));
    }

    function &source_titleEndsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('node_source_title', $str, '$'));
    }

    function &source_titleContains($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('node_source_title', $str));
    }

    function &source_titleIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('node_source_title', $values));
    }

    function &source_titleNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('node_source_title', $values));
    }

    function &content_syntaxIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_content_syntax', $value));
    }

    function &content_syntaxStartsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('node_content_syntax', $str, '^'));
    }

    function &content_syntaxEndsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('node_content_syntax', $str, '$'));
    }

    function &content_syntaxContains($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('node_content_syntax', $str));
    }

    function &content_syntaxIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('node_content_syntax', $values));
    }

    function &content_syntaxNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('node_content_syntax', $values));
    }

    function &bodyStartsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('node_body', $str, '^'));
    }

    function &bodyEndsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('node_body', $str, '$'));
    }

    function &bodyContains($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('node_body', $str));
    }

    function &body_htmlStartsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('node_body_html', $str, '^'));
    }

    function &body_htmlEndsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('node_body_html', $str, '$'));
    }

    function &body_htmlContains($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('node_body_html', $str));
    }

    function &teaserStartsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('node_teaser', $str, '^'));
    }

    function &teaserEndsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('node_teaser', $str, '$'));
    }

    function &teaserContains($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('node_teaser', $str));
    }

    function &teaser_htmlStartsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('node_teaser_html', $str, '^'));
    }

    function &teaser_htmlEndsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('node_teaser_html', $str, '$'));
    }

    function &teaser_htmlContains($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('node_teaser_html', $str));
    }

    function &publishedIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_published', $value));
    }

    function &publishedIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_published', $value, '>'));
    }

    function &publishedIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_published', $value, '<'));
    }

    function &publishedIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_published', $value, '>='));
    }

    function &publishedIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_published', $value, '<='));
    }

    function &publishedIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('node_published', $values));
    }

    function &publishedNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('node_published', $values));
    }

    function &allow_commentsIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_allow_comments', $value));
    }

    function &allow_commentsIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_allow_comments', $value, '>'));
    }

    function &allow_commentsIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_allow_comments', $value, '<'));
    }

    function &allow_commentsIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_allow_comments', $value, '>='));
    }

    function &allow_commentsIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_allow_comments', $value, '<='));
    }

    function &allow_commentsIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('node_allow_comments', $values));
    }

    function &allow_commentsNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('node_allow_comments', $values));
    }

    function &allow_trackbacksIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_allow_trackbacks', $value));
    }

    function &allow_trackbacksIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_allow_trackbacks', $value, '>'));
    }

    function &allow_trackbacksIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_allow_trackbacks', $value, '<'));
    }

    function &allow_trackbacksIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_allow_trackbacks', $value, '>='));
    }

    function &allow_trackbacksIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_allow_trackbacks', $value, '<='));
    }

    function &allow_trackbacksIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('node_allow_trackbacks', $values));
    }

    function &allow_trackbacksNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('node_allow_trackbacks', $values));
    }

    function &allow_editIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_allow_edit', $value));
    }

    function &allow_editIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_allow_edit', $value, '>'));
    }

    function &allow_editIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_allow_edit', $value, '<'));
    }

    function &allow_editIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_allow_edit', $value, '>='));
    }

    function &allow_editIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_allow_edit', $value, '<='));
    }

    function &allow_editIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('node_allow_edit', $values));
    }

    function &allow_editNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('node_allow_edit', $values));
    }

    function &statusIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_status', $value));
    }

    function &statusIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_status', $value, '>'));
    }

    function &statusIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_status', $value, '<'));
    }

    function &statusIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_status', $value, '>='));
    }

    function &statusIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_status', $value, '<='));
    }

    function &statusIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('node_status', $values));
    }

    function &statusNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('node_status', $values));
    }

    function &hiddenIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_hidden', $value));
    }

    function &hiddenIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_hidden', $value, '>'));
    }

    function &hiddenIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_hidden', $value, '<'));
    }

    function &hiddenIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_hidden', $value, '>='));
    }

    function &hiddenIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_hidden', $value, '<='));
    }

    function &hiddenIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('node_hidden', $values));
    }

    function &hiddenNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('node_hidden', $values));
    }

    function &priorityIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_priority', $value));
    }

    function &priorityIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_priority', $value, '>'));
    }

    function &priorityIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_priority', $value, '<'));
    }

    function &priorityIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_priority', $value, '>='));
    }

    function &priorityIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_priority', $value, '<='));
    }

    function &priorityIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('node_priority', $values));
    }

    function &priorityNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('node_priority', $values));
    }

    function &viewsIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_views', $value));
    }

    function &viewsIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_views', $value, '>'));
    }

    function &viewsIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_views', $value, '<'));
    }

    function &viewsIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_views', $value, '>='));
    }

    function &viewsIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_views', $value, '<='));
    }

    function &viewsIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('node_views', $values));
    }

    function &viewsNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('node_views', $values));
    }

    function &category_idIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_category_id', $value));
    }

    function &category_idIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_category_id', $value, '>'));
    }

    function &category_idIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_category_id', $value, '<'));
    }

    function &category_idIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_category_id', $value, '>='));
    }

    function &category_idIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_category_id', $value, '<='));
    }

    function &category_idIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('node_category_id', $values));
    }

    function &category_idNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('node_category_id', $values));
    }

    function &useridIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_userid', $value));
    }

    function &useridStartsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('node_userid', $str, '^'));
    }

    function &useridEndsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('node_userid', $str, '$'));
    }

    function &useridContains($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('node_userid', $str));
    }

    function &useridIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('node_userid', $values));
    }

    function &useridNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('node_userid', $values));
    }

    function &comment_countIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_comment_count', $value));
    }

    function &comment_countIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_comment_count', $value, '>'));
    }

    function &comment_countIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_comment_count', $value, '<'));
    }

    function &comment_countIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_comment_count', $value, '>='));
    }

    function &comment_countIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_comment_count', $value, '<='));
    }

    function &comment_countIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('node_comment_count', $values));
    }

    function &comment_countNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('node_comment_count', $values));
    }

    function &comment_lastIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_comment_last', $value));
    }

    function &comment_lastIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_comment_last', $value, '>'));
    }

    function &comment_lastIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_comment_last', $value, '<'));
    }

    function &comment_lastIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_comment_last', $value, '>='));
    }

    function &comment_lastIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_comment_last', $value, '<='));
    }

    function &comment_lastIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('node_comment_last', $values));
    }

    function &comment_lastNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('node_comment_last', $values));
    }

    function &comment_lasttimeIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_comment_lasttime', $value));
    }

    function &comment_lasttimeIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_comment_lasttime', $value, '>'));
    }

    function &comment_lasttimeIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_comment_lasttime', $value, '<'));
    }

    function &comment_lasttimeIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_comment_lasttime', $value, '>='));
    }

    function &comment_lasttimeIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_comment_lasttime', $value, '<='));
    }

    function &comment_lasttimeIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('node_comment_lasttime', $values));
    }

    function &comment_lasttimeNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('node_comment_lasttime', $values));
    }

    function &trackback_countIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_trackback_count', $value));
    }

    function &trackback_countIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_trackback_count', $value, '>'));
    }

    function &trackback_countIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_trackback_count', $value, '<'));
    }

    function &trackback_countIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_trackback_count', $value, '>='));
    }

    function &trackback_countIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_trackback_count', $value, '<='));
    }

    function &trackback_countIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('node_trackback_count', $values));
    }

    function &trackback_countNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('node_trackback_count', $values));
    }

    function &trackback_lastIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_trackback_last', $value));
    }

    function &trackback_lastIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_trackback_last', $value, '>'));
    }

    function &trackback_lastIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_trackback_last', $value, '<'));
    }

    function &trackback_lastIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_trackback_last', $value, '>='));
    }

    function &trackback_lastIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_trackback_last', $value, '<='));
    }

    function &trackback_lastIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('node_trackback_last', $values));
    }

    function &trackback_lastNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('node_trackback_last', $values));
    }

    function &trackback_lasttimeIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_trackback_lasttime', $value));
    }

    function &trackback_lasttimeIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_trackback_lasttime', $value, '>'));
    }

    function &trackback_lasttimeIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_trackback_lasttime', $value, '<'));
    }

    function &trackback_lasttimeIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_trackback_lasttime', $value, '>='));
    }

    function &trackback_lasttimeIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_trackback_lasttime', $value, '<='));
    }

    function &trackback_lasttimeIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('node_trackback_lasttime', $values));
    }

    function &trackback_lasttimeNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('node_trackback_lasttime', $values));
    }

    function &vote_countIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_vote_count', $value));
    }

    function &vote_countIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_vote_count', $value, '>'));
    }

    function &vote_countIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_vote_count', $value, '<'));
    }

    function &vote_countIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_vote_count', $value, '>='));
    }

    function &vote_countIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_vote_count', $value, '<='));
    }

    function &vote_countIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('node_vote_count', $values));
    }

    function &vote_countNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('node_vote_count', $values));
    }

    function &vote_lastIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_vote_last', $value));
    }

    function &vote_lastIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_vote_last', $value, '>'));
    }

    function &vote_lastIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_vote_last', $value, '<'));
    }

    function &vote_lastIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_vote_last', $value, '>='));
    }

    function &vote_lastIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_vote_last', $value, '<='));
    }

    function &vote_lastIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('node_vote_last', $values));
    }

    function &vote_lastNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('node_vote_last', $values));
    }

    function &vote_lasttimeIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_vote_lasttime', $value));
    }

    function &vote_lasttimeIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_vote_lasttime', $value, '>'));
    }

    function &vote_lasttimeIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_vote_lasttime', $value, '<'));
    }

    function &vote_lasttimeIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_vote_lasttime', $value, '>='));
    }

    function &vote_lasttimeIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_vote_lasttime', $value, '<='));
    }

    function &vote_lasttimeIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('node_vote_lasttime', $values));
    }

    function &vote_lasttimeNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('node_vote_lasttime', $values));
    }

    function &view_countIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_view_count', $value));
    }

    function &view_countIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_view_count', $value, '>'));
    }

    function &view_countIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_view_count', $value, '<'));
    }

    function &view_countIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_view_count', $value, '>='));
    }

    function &view_countIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_view_count', $value, '<='));
    }

    function &view_countIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('node_view_count', $values));
    }

    function &view_countNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('node_view_count', $values));
    }

    function &view_lastIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_view_last', $value));
    }

    function &view_lastIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_view_last', $value, '>'));
    }

    function &view_lastIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_view_last', $value, '<'));
    }

    function &view_lastIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_view_last', $value, '>='));
    }

    function &view_lastIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_view_last', $value, '<='));
    }

    function &view_lastIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('node_view_last', $values));
    }

    function &view_lastNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('node_view_last', $values));
    }

    function &view_lasttimeIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_view_lasttime', $value));
    }

    function &view_lasttimeIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_view_lasttime', $value, '>'));
    }

    function &view_lasttimeIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_view_lasttime', $value, '<'));
    }

    function &view_lasttimeIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_view_lasttime', $value, '>='));
    }

    function &view_lasttimeIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('node_view_lasttime', $value, '<='));
    }

    function &view_lasttimeIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('node_view_lasttime', $values));
    }

    function &view_lasttimeNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('node_view_lasttime', $values));
    }
}