<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

require_once 'Sabai/Model/EntityCollection/Decorator/ForeignEntities.php';

class Xigg_Model_NodesWithVotesBase extends Sabai_Model_EntityCollection_Decorator_ForeignEntities
{
    function Xigg_Model_NodesWithVotesBase(&$collection)
    {
        parent::Sabai_Model_EntityCollection_Decorator_ForeignEntities('vote_node_id', 'Vote', 'vote_node_id', $collection);
    }
}