<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
Xigg/library/Xigg/Model/RoleForm.php
*/
class Xigg_Model_RoleFormBase extends Sabai_Model_EntityForm
{
    function onInit($params)
    {
        require_once 'Sabai/Form/Element/InputText.php';
        $this->addElement(new Sabai_Form_Element_InputText('name', 80, 255), _('Name'));
        require_once 'Sabai/Form/Element/Text.php';
        $this->addElement(new Sabai_Form_Element_Text('permissions'), _('Permissions'));
        require_once 'Sabai/Form/Element/Text.php';
        $this->addElement(new Sabai_Form_Element_Text('system'), _('System'));
        $this->_onInit($params);
    }

    function onEntity(&$entity)
    {
        if ($this->hasElement('name')) {
            $this->setValueFor('name', $entity->getVar('name'));
        }
        if ($this->hasElement('permissions')) {
            $this->setValueFor('permissions', $entity->getVar('permissions'));
        }
        if ($this->hasElement('system')) {
            $this->setValueFor('system', $entity->getVar('system'));
        }
        $this->_onEntity($entity);
    }

    function onFillEntity(&$entity)
    {
        $vars = array();
        foreach (array('name' => 'name', 'permissions' => 'permissions', 'system' => 'system') as $var_name => $form_name) {
            if ($this->hasElement($form_name)) {
                $vars[$var_name] = $this->getValueFor($form_name);
            }
        }
        $entity->setVars($vars);
        $this->_onFillEntity($entity);
    }

    function _onInit($params){}
    function _onEntity(&$entity){}
    function _onFillEntity(&$entity){}
}