<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
Xigg/library/Xigg/Model/RoleGateway.php
*/
class Xigg_Model_RoleGatewayBase extends Sabai_Model_Gateway
{
    function getName()
    {
        return 'role';
    }

    function getFields()
    {
        return array('role_id' => SABAI_MODEL_KEY_TYPE_INT, 'role_created' => SABAI_MODEL_KEY_TYPE_INT, 'role_updated' => SABAI_MODEL_KEY_TYPE_INT, 'role_name' => SABAI_MODEL_KEY_TYPE_VARCHAR, 'role_permissions' => SABAI_MODEL_KEY_TYPE_TEXT, 'role_system' => SABAI_MODEL_KEY_TYPE_INT, 'role_member_count' => SABAI_MODEL_KEY_TYPE_INT, 'role_member_last' => SABAI_MODEL_KEY_TYPE_INT, 'role_member_lasttime' => SABAI_MODEL_KEY_TYPE_INT);
    }

    function _getSelectByIdQuery($id, $fields)
    {
        $fields = empty($fields) ? '*' : implode(', t.', $fields);
        return sprintf('SELECT t.%s FROM %srole t WHERE role_id = %d', $fields, $this->_db->getResourcePrefix(), $id);
    }

    function _getSelectByCriteriaQuery($criteriaStr, $fields)
    {
        $fields = empty($fields) ? '*' : implode(', t.', $fields);
        return sprintf('SELECT t.%1$s FROM %2$srole t WHERE %3$s', $fields, $this->_db->getResourcePrefix(), $criteriaStr);
    }

    function _getInsertQuery($values)
    {
        $values['role_created'] = time();
        $values['role_updated'] = 0;
        $values['role_member_lasttime'] = $values['role_created'];
        return sprintf("INSERT INTO %srole(role_created, role_updated, role_name, role_permissions, role_system, role_member_count, role_member_last, role_member_lasttime) VALUES(%d, %d, %s, %s, %d, %d, %d, %d)", $this->_db->getResourcePrefix(), $values['role_created'], $values['role_updated'], $this->_db->escapeString($values['role_name']), $this->_db->escapeString($values['role_permissions']), $values['role_system'], $values['role_member_count'], $values['role_member_last'], $values['role_member_lasttime']);
    }

    function _getUpdateQuery($id, $values)
    {
        $last_update = $values['role_updated'];
        $values['role_updated'] = time();
        return sprintf("UPDATE %srole SET role_updated = %d, role_name = %s, role_permissions = %s, role_system = %d, role_member_count = %d, role_member_last = %d, role_member_lasttime = %d WHERE role_id = %d AND role_updated = %d", $this->_db->getResourcePrefix(), $values['role_updated'], $this->_db->escapeString($values['role_name']), $this->_db->escapeString($values['role_permissions']), $values['role_system'], $values['role_member_count'], $values['role_member_last'], $values['role_member_lasttime'], $id, $last_update);
    }

    function _getDeleteQuery($id)
    {
        return sprintf('DELETE FROM %1$srole WHERE role_id = %2$d', $this->_db->getResourcePrefix(), $id);
    }

    function _getUpdateByCriteriaQuery($criteriaStr, $sets)
    {
        $sets['role_updated'] = 'role_updated=' . time();
        return sprintf('UPDATE %srole SET %s WHERE %s', $this->_db->getResourcePrefix(), implode(',', $sets), $criteriaStr);
    }

    function _getDeleteByCriteriaQuery($criteriaStr)
    {
        return sprintf('DELETE FROM %1$srole WHERE %2$s', $this->_db->getResourcePrefix(), $criteriaStr);
    }

    function _getCountByCriteriaQuery($criteriaStr)
    {
        return sprintf('SELECT COUNT(*) FROM %1$srole WHERE %2$s', $this->_db->getResourcePrefix(), $criteriaStr);
    }

    function _beforeDeleteTrigger1($id, $old)
    {
        return $this->_db->exec(sprintf('DELETE %1$smember FROM %1$smember WHERE %1$smember.member_role_id = %2$d', $this->_db->getResourcePrefix(), $id), false);
    }

    function _beforeDeleteTrigger($id, $old)
    {
        if (!$this->_beforeDeleteTrigger1($id, $old)) {
            return false;
        }
        return true;
    }
}