<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
Xigg/library/Xigg/Model/RoleCriteria.php
*/
require_once 'Sabai/Model/EntityCriteria.php';

class Xigg_Model_RoleCriteriaBase extends Sabai_Model_EntityCriteria
{

    function &idIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('role_id', $value));
    }

    function &idIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('role_id', $value, '>'));
    }

    function &idIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('role_id', $value, '<'));
    }

    function &idIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('role_id', $value, '>='));
    }

    function &idIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('role_id', $value, '<='));
    }

    function &idIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('role_id', $values));
    }

    function &idNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('role_id', $values));
    }

    function &createdIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('role_created', $value));
    }

    function &createdIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('role_created', $value, '>'));
    }

    function &createdIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('role_created', $value, '<'));
    }

    function &createdIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('role_created', $value, '>='));
    }

    function &createdIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('role_created', $value, '<='));
    }

    function &createdIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('role_created', $values));
    }

    function &createdNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('role_created', $values));
    }

    function &updatedIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('role_updated', $value));
    }

    function &updatedIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('role_updated', $value, '>'));
    }

    function &updatedIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('role_updated', $value, '<'));
    }

    function &updatedIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('role_updated', $value, '>='));
    }

    function &updatedIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('role_updated', $value, '<='));
    }

    function &updatedIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('role_updated', $values));
    }

    function &updatedNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('role_updated', $values));
    }

    function &nameIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('role_name', $value));
    }

    function &nameStartsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('role_name', $str, '^'));
    }

    function &nameEndsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('role_name', $str, '$'));
    }

    function &nameContains($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('role_name', $str));
    }

    function &nameIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('role_name', $values));
    }

    function &nameNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('role_name', $values));
    }

    function &permissionsStartsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('role_permissions', $str, '^'));
    }

    function &permissionsEndsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('role_permissions', $str, '$'));
    }

    function &permissionsContains($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('role_permissions', $str));
    }

    function &systemIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('role_system', $value));
    }

    function &systemIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('role_system', $value, '>'));
    }

    function &systemIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('role_system', $value, '<'));
    }

    function &systemIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('role_system', $value, '>='));
    }

    function &systemIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('role_system', $value, '<='));
    }

    function &systemIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('role_system', $values));
    }

    function &systemNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('role_system', $values));
    }

    function &member_countIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('role_member_count', $value));
    }

    function &member_countIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('role_member_count', $value, '>'));
    }

    function &member_countIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('role_member_count', $value, '<'));
    }

    function &member_countIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('role_member_count', $value, '>='));
    }

    function &member_countIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('role_member_count', $value, '<='));
    }

    function &member_countIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('role_member_count', $values));
    }

    function &member_countNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('role_member_count', $values));
    }

    function &member_lastIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('role_member_last', $value));
    }

    function &member_lastIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('role_member_last', $value, '>'));
    }

    function &member_lastIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('role_member_last', $value, '<'));
    }

    function &member_lastIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('role_member_last', $value, '>='));
    }

    function &member_lastIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('role_member_last', $value, '<='));
    }

    function &member_lastIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('role_member_last', $values));
    }

    function &member_lastNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('role_member_last', $values));
    }

    function &member_lasttimeIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('role_member_lasttime', $value));
    }

    function &member_lasttimeIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('role_member_lasttime', $value, '>'));
    }

    function &member_lasttimeIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('role_member_lasttime', $value, '<'));
    }

    function &member_lasttimeIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('role_member_lasttime', $value, '>='));
    }

    function &member_lasttimeIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('role_member_lasttime', $value, '<='));
    }

    function &member_lasttimeIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('role_member_lasttime', $values));
    }

    function &member_lasttimeNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('role_member_lasttime', $values));
    }
}