<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

require_once 'Sabai/Model/EntityCollection/Decorator/ForeignEntities.php';

class Xigg_Model_RolesWithMembersBase extends Sabai_Model_EntityCollection_Decorator_ForeignEntities
{
    function Xigg_Model_RolesWithMembersBase(&$collection)
    {
        parent::Sabai_Model_EntityCollection_Decorator_ForeignEntities('member_role_id', 'Member', 'member_role_id', $collection);
    }
}