<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
Xigg/library/Xigg/Model/TagForm.php
*/
class Xigg_Model_TagFormBase extends Sabai_Model_EntityForm
{
    function onInit($params)
    {
        require_once 'Sabai/Form/Element/InputText.php';
        $this->addElement(new Sabai_Form_Element_InputText('name', 80, 255), _('Name'));
        require_once 'Sabai/Form/Element/SelectEntity.php';
        $element =& new Sabai_Form_Element_SelectEntity($this->_model, 'Node', 'Nodes', 5, true);
        $this->addElement($element, _('Node'));
        $this->_onInit($params);
    }

    function onEntity(&$entity)
    {
        if ($this->hasElement('name')) {
            $this->setValueFor('name', $entity->getVar('name'));
        }
        if ($this->hasElement('Nodes')) {
            $node_entities =& $entity->get('Nodes');
            $value = array();
            $node_entities->rewind();
            while ($obj =& $node_entities->getNext()) {
                $value[] = $obj->getId();
                unset($obj);
            }
            $this->setValueFor('Nodes', $value);
        }
        $this->_onEntity($entity);
    }

    function onFillEntity(&$entity)
    {
        $vars = array();
        foreach (array('name' => 'name') as $var_name => $form_name) {
            if ($this->hasElement($form_name)) {
                $vars[$var_name] = $this->getValueFor($form_name);
            }
        }
        $entity->setVars($vars);
        if ($this->hasElement('Nodes')) {
            $entity->set('Nodes', $this->getValueFor('Nodes'));
        }
        $this->_onFillEntity($entity);
    }

    function _onInit($params){}
    function _onEntity(&$entity){}
    function _onFillEntity(&$entity){}
}