<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
Xigg/library/Xigg/Model/TagGateway.php
*/
class Xigg_Model_TagGatewayBase extends Sabai_Model_Gateway
{
    function getName()
    {
        return 'tag';
    }

    function getFields()
    {
        return array('tag_id' => SABAI_MODEL_KEY_TYPE_INT, 'tag_created' => SABAI_MODEL_KEY_TYPE_INT, 'tag_updated' => SABAI_MODEL_KEY_TYPE_INT, 'tag_name' => SABAI_MODEL_KEY_TYPE_VARCHAR);
    }

    function _getSelectByIdQuery($id, $fields)
    {
        $fields = empty($fields) ? '*' : implode(', t.', $fields);
        return sprintf('SELECT t.%s FROM %stag t WHERE tag_id = %d', $fields, $this->_db->getResourcePrefix(), $id);
    }

    function _getSelectByCriteriaQuery($criteriaStr, $fields)
    {
        $fields = empty($fields) ? '*' : implode(', t.', $fields);
        return sprintf('SELECT t.%1$s FROM %2$stag t WHERE %3$s', $fields, $this->_db->getResourcePrefix(), $criteriaStr);
    }

    function _getInsertQuery($values)
    {
        $values['tag_created'] = time();
        $values['tag_updated'] = 0;
        return sprintf("INSERT INTO %stag(tag_created, tag_updated, tag_name) VALUES(%d, %d, %s)", $this->_db->getResourcePrefix(), $values['tag_created'], $values['tag_updated'], $this->_db->escapeString($values['tag_name']));
    }

    function _getUpdateQuery($id, $values)
    {
        $last_update = $values['tag_updated'];
        $values['tag_updated'] = time();
        return sprintf("UPDATE %stag SET tag_updated = %d, tag_name = %s WHERE tag_id = %d AND tag_updated = %d", $this->_db->getResourcePrefix(), $values['tag_updated'], $this->_db->escapeString($values['tag_name']), $id, $last_update);
    }

    function _getDeleteQuery($id)
    {
        return sprintf('DELETE FROM %1$stag WHERE tag_id = %2$d', $this->_db->getResourcePrefix(), $id);
    }

    function _getUpdateByCriteriaQuery($criteriaStr, $sets)
    {
        $sets['tag_updated'] = 'tag_updated=' . time();
        return sprintf('UPDATE %stag SET %s WHERE %s', $this->_db->getResourcePrefix(), implode(',', $sets), $criteriaStr);
    }

    function _getDeleteByCriteriaQuery($criteriaStr)
    {
        return sprintf('DELETE FROM %1$stag WHERE %2$s', $this->_db->getResourcePrefix(), $criteriaStr);
    }

    function _getCountByCriteriaQuery($criteriaStr)
    {
        return sprintf('SELECT COUNT(*) FROM %1$stag WHERE %2$s', $this->_db->getResourcePrefix(), $criteriaStr);
    }

    function _beforeDeleteTrigger1($id, $old)
    {
        return $this->_db->exec(sprintf('DELETE %1$snode2tag FROM %1$snode2tag WHERE %1$snode2tag.node2tag_tag_id = %2$d', $this->_db->getResourcePrefix(), $id), false);
    }

    function _beforeDeleteTrigger($id, $old)
    {
        if (!$this->_beforeDeleteTrigger1($id, $old)) {
            return false;
        }
        return true;
    }
}