<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

require_once 'Sabai/Model/EntityCollection/Decorator/AssocEntities.php';

class Xigg_Model_TagsWithNodesBase extends Sabai_Model_EntityCollection_Decorator_AssocEntities
{
    function Xigg_Model_TagsWithNodesBase(&$collection)
    {
        parent::Sabai_Model_EntityCollection_Decorator_AssocEntities('Node2tag', 'node2tag_tag_id', 'node', 'Node', $collection);
    }
}