<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
Xigg/library/Xigg/Model/TrackbackCriteria.php
*/
require_once 'Sabai/Model/EntityCriteria.php';

class Xigg_Model_TrackbackCriteriaBase extends Sabai_Model_EntityCriteria
{

    function &idIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('trackback_id', $value));
    }

    function &idIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('trackback_id', $value, '>'));
    }

    function &idIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('trackback_id', $value, '<'));
    }

    function &idIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('trackback_id', $value, '>='));
    }

    function &idIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('trackback_id', $value, '<='));
    }

    function &idIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('trackback_id', $values));
    }

    function &idNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('trackback_id', $values));
    }

    function &createdIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('trackback_created', $value));
    }

    function &createdIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('trackback_created', $value, '>'));
    }

    function &createdIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('trackback_created', $value, '<'));
    }

    function &createdIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('trackback_created', $value, '>='));
    }

    function &createdIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('trackback_created', $value, '<='));
    }

    function &createdIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('trackback_created', $values));
    }

    function &createdNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('trackback_created', $values));
    }

    function &updatedIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('trackback_updated', $value));
    }

    function &updatedIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('trackback_updated', $value, '>'));
    }

    function &updatedIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('trackback_updated', $value, '<'));
    }

    function &updatedIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('trackback_updated', $value, '>='));
    }

    function &updatedIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('trackback_updated', $value, '<='));
    }

    function &updatedIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('trackback_updated', $values));
    }

    function &updatedNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('trackback_updated', $values));
    }

    function &titleIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('trackback_title', $value));
    }

    function &titleStartsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('trackback_title', $str, '^'));
    }

    function &titleEndsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('trackback_title', $str, '$'));
    }

    function &titleContains($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('trackback_title', $str));
    }

    function &titleIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('trackback_title', $values));
    }

    function &titleNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('trackback_title', $values));
    }

    function &excerptStartsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('trackback_excerpt', $str, '^'));
    }

    function &excerptEndsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('trackback_excerpt', $str, '$'));
    }

    function &excerptContains($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('trackback_excerpt', $str));
    }

    function &urlIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('trackback_url', $value));
    }

    function &urlStartsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('trackback_url', $str, '^'));
    }

    function &urlEndsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('trackback_url', $str, '$'));
    }

    function &urlContains($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('trackback_url', $str));
    }

    function &urlIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('trackback_url', $values));
    }

    function &urlNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('trackback_url', $values));
    }

    function &blog_nameIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('trackback_blog_name', $value));
    }

    function &blog_nameStartsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('trackback_blog_name', $str, '^'));
    }

    function &blog_nameEndsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('trackback_blog_name', $str, '$'));
    }

    function &blog_nameContains($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('trackback_blog_name', $str));
    }

    function &blog_nameIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('trackback_blog_name', $values));
    }

    function &blog_nameNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('trackback_blog_name', $values));
    }

    function &node_idIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('trackback_node_id', $value));
    }

    function &node_idIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('trackback_node_id', $value, '>'));
    }

    function &node_idIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('trackback_node_id', $value, '<'));
    }

    function &node_idIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('trackback_node_id', $value, '>='));
    }

    function &node_idIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('trackback_node_id', $value, '<='));
    }

    function &node_idIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('trackback_node_id', $values));
    }

    function &node_idNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('trackback_node_id', $values));
    }
}