<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

require_once 'Sabai/Model/EntityCollection/Decorator/ForeignEntity.php';

class Xigg_Model_TrackbacksWithNodeBase extends Sabai_Model_EntityCollection_Decorator_ForeignEntity
{
    function Xigg_Model_TrackbacksWithNodeBase(&$collection)
    {
        parent::Sabai_Model_EntityCollection_Decorator_ForeignEntity('node_id', 'Node', 'node_id', $collection);
    }
}