<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
Xigg/library/Xigg/Model/Trackback.php
*/
class Xigg_Model_TrackbackBase extends Sabai_Model_Entity
{
    function Xigg_Model_TrackbackBase(&$model)
    {
        parent::Sabai_Model_Entity('Trackback', $model);
        $this->_vars = array('trackback_id' => 0, 'trackback_created' => 0, 'trackback_updated' => 0, 'trackback_title' => null, 'trackback_excerpt' => null, 'trackback_url' => null, 'trackback_blog_name' => null, 'trackback_node_id' => null);
    }

    function varNames()
    {
        return array('id' => _('Id'), 'created' => _('Created'), 'updated' => _('Updated'), 'title' => _('Title'), 'excerpt' => _('Excerpt'), 'url' => _('Url'), 'blog_name' => _('Blog name'), 'node_id' => _('Node id'));
    }

    function propertyNames()
    {
        return array('title' => _('Title'), 'excerpt' => _('Excerpt'), 'url' => _('Url'), 'blog_name' => _('Blog name'), 'Node' => 'Node');
    }

    function localPropertyNames()
    {
        return array('title' => _('Title'), 'excerpt' => _('Excerpt'), 'url' => _('Url'), 'blog_name' => _('Blog name'));
    }

    function getId()
    {
        return $this->getVar('id');
    }

    function setId($value)
    {
        $this->setVar('id', $value);
    }

    function getTimeCreated()
    {
        return $this->getVar('created');
    }

    function getTimeUpdated()
    {
        return $this->getVar('updated');
    }

    function getLabel()
    {
        return $this->getVar('title');
    }

    function setLabel($value)
    {
        $this->setVar('title', $value);
    }

    function assignNode(&$entity)
    {
        if ($entity->getName() != 'Node') {
            return false;
        }
        return $this->_assignEntity('node_id', $entity);
    }

    function unassignNode()
    {
        return $this->_unassignEntity('node_id');
    }

    function &_fetchNode()
    {
        if (!isset($this->_objects['Node'])) {
            $this->_objects['Node'] =& $this->_fetchEntity('Node', 'node_id');
        }
        return $this->_objects['Node'];
    }

    function _getVar($name)
    {
        return $this->_vars['trackback_' . $name];
    }

    function _setVar($name, $value)
    {
        switch ($name) {
        case 'id':
            $this->_vars['trackback_id'] = $value;
            break;
        case 'title':
            $this->_vars['trackback_title'] = trim($value);
            break;
        case 'excerpt':
            $this->_vars['trackback_excerpt'] = trim($value);
            break;
        case 'url':
            $this->_vars['trackback_url'] = trim($value);
            break;
        case 'blog_name':
            $this->_vars['trackback_blog_name'] = trim($value);
            break;
        case 'node_id':
            $this->_vars['trackback_node_id'] = $value;
            break;
        default:
            trigger_error(sprintf('Error trying to set value for variable %s. This variable is either read-only or does not exist for this entity', $name), E_USER_WARNING);
            return false;
        }
        return true;
    }

    function &__get($name)
    {
        $ret = null;
        settype($name, 'string');
        switch ($name) {
        case 'title':
            $ret = $this->getVar('title');
            break;
        case 'excerpt':
            $ret = $this->getVar('excerpt');
            break;
        case 'url':
            $ret = $this->getVar('url');
            break;
        case 'blog_name':
            $ret = $this->getVar('blog_name');
            break;
        case 'Node':
            $ret =& $this->_fetchNode();
            break;
        default:
        }
        return $ret;
    }

    function __set($name, $value)
    {
        settype($name, 'string');
        switch ($name) {
        case 'title':
            $this->setVar('title', $value);
            break;
        case 'excerpt':
            $this->setVar('excerpt', $value);
            break;
        case 'url':
            $this->setVar('url', $value);
            break;
        case 'blog_name':
            $this->setVar('blog_name', $value);
            break;
        case 'Node':
            if (is_array($value)) {
                $entity =& $value[0];
            } else {
                $entity =& $value;
            }
            $this->assignNode($entity);
            break;
        default:
        }
    }

    function initVar($name, $value)
    {
        switch ($name) {
        case 'trackback_id':
            $this->_vars['trackback_id'] = $value;
            break;
        case 'trackback_created':
            $this->_vars['trackback_created'] = $value;
            break;
        case 'trackback_updated':
            $this->_vars['trackback_updated'] = $value;
            break;
        case 'trackback_title':
            $this->_vars['trackback_title'] = $value;
            break;
        case 'trackback_excerpt':
            $this->_vars['trackback_excerpt'] = $value;
            break;
        case 'trackback_url':
            $this->_vars['trackback_url'] = $value;
            break;
        case 'trackback_blog_name':
            $this->_vars['trackback_blog_name'] = $value;
            break;
        case 'trackback_node_id':
            $this->_vars['trackback_node_id'] = $value;
            break;
        default:
        }
    }
}

class Xigg_Model_TrackbackRepositoryBase extends Sabai_Model_EntityRepository
{
    function Xigg_Model_TrackbackRepositoryBase(&$model)
    {
        parent::Sabai_Model_EntityRepository('Trackback', $model);
    }

    function &fetchByNode($id, $limit = 0, $offset = 0, $sort = null, $order = null)
    {
        $it =& $this->_fetchByForeign('trackback_node_id', $id, $limit, $offset, $sort, $order);
        return $it;
    }

    function &paginateByNode($id, $perpage = 10, $sort = null, $order = null)
    {
        $it =& $this->_paginateByEntity('Node', $id, $perpage, $sort, $order);
        return $it;
    }

    function countByNode($id)
    {
        return $this->_countByForeign('trackback_node_id', $id);
    }

    function &fetchByNodeAndCriteria($id, &$criteria, $limit = 0, $offset = 0, $sort = null, $order = null)
    {
        $it =& $this->_fetchByForeignAndCriteria('trackback_node_id', $id, $criteria, $limit, $offset, $sort, $order);
        return $it;
    }

    function &paginateByNodeAndCriteria($id, &$criteria, $perpage = 10, $sort = null, $order = null)
    {
        $it =& $this->_paginateByEntityAndCriteria('Node', $id, $criteria, $perpage, $sort, $order);
        return $it;
    }

    function countByNodeAndCriteria($id, &$criteria)
    {
        return $this->_countByForeignAndCriteria('trackback_node_id', $id, $criteria);
    }

    function &_getCollectionByRowset(&$rs)
    {
        $collection =& new Xigg_Model_TrackbacksByRowset($rs, $this->_model->create('Trackback'), $this->_model);
        return $collection;
    }

    function &createCollection($entities = array(), $key = 0)
    {
        $collection =& new Xigg_Model_Trackbacks($this->_model, $entities, $key);
        return $collection;
    }
}

class Xigg_Model_TrackbacksByRowset extends Sabai_Model_EntityCollection_Rowset
{
    function Xigg_Model_TrackbacksByRowset(&$rs, &$emptyEntity, &$model, $key = 0)
    {
        parent::Sabai_Model_EntityCollection_Rowset('Trackbacks', $rs, $emptyEntity, $model, $key);
    }

    function _loadRow(&$entity, $row)
    {
        $entity->initVars($row);
    }
}

class Xigg_Model_Trackbacks extends Sabai_Model_EntityCollection_Array
{
    function Xigg_Model_Trackbacks(&$model, $entities = array(), $key = 0)
    {
        parent::Sabai_Model_EntityCollection_Array($model, 'Trackbacks', $entities, $key);
    }
}