<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
Xigg/library/Xigg/Model/TrackbackForm.php
*/
class Xigg_Model_TrackbackFormBase extends Sabai_Model_EntityForm
{
    function onInit($params)
    {
        require_once 'Sabai/Form/Element/InputText.php';
        $this->addElement(new Sabai_Form_Element_InputText('title', 80, 255), _('Title'));
        require_once 'Sabai/Form/Element/Textarea.php';
        $this->addElement(new Sabai_Form_Element_Textarea('excerpt', 10, 60), _('Excerpt'));
        require_once 'Sabai/Form/Element/InputText.php';
        $this->addElement(new Sabai_Form_Element_InputText('url', 80, 255), _('Url'));
        require_once 'Sabai/Form/Element/InputText.php';
        $this->addElement(new Sabai_Form_Element_InputText('blog_name', 80, 255), _('Blog name'));
        require_once 'Sabai/Form/Element/SelectEntity.php';
        $element =& new Sabai_Form_Element_SelectEntity($this->_model, 'Node', 'Node', 1);
        $this->addElement($element, _('node'));
        $this->_onInit($params);
    }

    function onEntity(&$entity)
    {
        if ($this->hasElement('title')) {
            $this->setValueFor('title', $entity->getVar('title'));
        }
        if ($this->hasElement('excerpt')) {
            $this->setValueFor('excerpt', $entity->getVar('excerpt'));
        }
        if ($this->hasElement('url')) {
            $this->setValueFor('url', $entity->getVar('url'));
        }
        if ($this->hasElement('blog_name')) {
            $this->setValueFor('blog_name', $entity->getVar('blog_name'));
        }
        if ($this->hasElement('Node')) {
            $this->setValueFor('Node', $entity->getVar('node_id'));
        }
        $this->_onEntity($entity);
    }

    function onFillEntity(&$entity)
    {
        $vars = array();
        foreach (array('title' => 'title', 'excerpt' => 'excerpt', 'url' => 'url', 'blog_name' => 'blog_name', 'node_id' => 'Node') as $var_name => $form_name) {
            if ($this->hasElement($form_name)) {
                $vars[$var_name] = $this->getValueFor($form_name);
            }
        }
        $entity->setVars($vars);
        $this->_onFillEntity($entity);
    }

    function _onInit($params){}
    function _onEntity(&$entity){}
    function _onFillEntity(&$entity){}
}