<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
Xigg/library/Xigg/Model/ViewForm.php
*/
class Xigg_Model_ViewFormBase extends Sabai_Model_EntityForm
{
    function onInit($params)
    {
        require_once 'Sabai/Form/Element/Text.php';
        $this->addElement(new Sabai_Form_Element_Text('uid'), _('Uid'));
        require_once 'Sabai/Form/Element/Text.php';
        $this->addElement(new Sabai_Form_Element_Text('last'), _('Last'));
        require_once 'Sabai/Form/Element/SelectEntity.php';
        $element =& new Sabai_Form_Element_SelectEntity($this->_model, 'Node', 'Node', 1);
        $this->addElement($element, _('node'));
        $this->_onInit($params);
    }

    function onEntity(&$entity)
    {
        if ($this->hasElement('uid')) {
            $this->setValueFor('uid', $entity->getVar('uid'));
        }
        if ($this->hasElement('last')) {
            $this->setValueFor('last', $entity->getVar('last'));
        }
        if ($this->hasElement('Node')) {
            $this->setValueFor('Node', $entity->getVar('node_id'));
        }
        $this->_onEntity($entity);
    }

    function onFillEntity(&$entity)
    {
        $vars = array();
        foreach (array('uid' => 'uid', 'last' => 'last', 'node_id' => 'Node') as $var_name => $form_name) {
            if ($this->hasElement($form_name)) {
                $vars[$var_name] = $this->getValueFor($form_name);
            }
        }
        $entity->setVars($vars);
        $this->_onFillEntity($entity);
    }

    function _onInit($params){}
    function _onEntity(&$entity){}
    function _onFillEntity(&$entity){}
}