<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
Xigg/library/Xigg/Model/ViewCriteria.php
*/
require_once 'Sabai/Model/EntityCriteria.php';

class Xigg_Model_ViewCriteriaBase extends Sabai_Model_EntityCriteria
{

    function &idIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('view_id', $value));
    }

    function &idIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('view_id', $value, '>'));
    }

    function &idIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('view_id', $value, '<'));
    }

    function &idIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('view_id', $value, '>='));
    }

    function &idIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('view_id', $value, '<='));
    }

    function &idIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('view_id', $values));
    }

    function &idNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('view_id', $values));
    }

    function &createdIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('view_created', $value));
    }

    function &createdIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('view_created', $value, '>'));
    }

    function &createdIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('view_created', $value, '<'));
    }

    function &createdIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('view_created', $value, '>='));
    }

    function &createdIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('view_created', $value, '<='));
    }

    function &createdIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('view_created', $values));
    }

    function &createdNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('view_created', $values));
    }

    function &updatedIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('view_updated', $value));
    }

    function &updatedIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('view_updated', $value, '>'));
    }

    function &updatedIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('view_updated', $value, '<'));
    }

    function &updatedIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('view_updated', $value, '>='));
    }

    function &updatedIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('view_updated', $value, '<='));
    }

    function &updatedIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('view_updated', $values));
    }

    function &updatedNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('view_updated', $values));
    }

    function &uidIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('view_uid', $value));
    }

    function &uidStartsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('view_uid', $str, '^'));
    }

    function &uidEndsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('view_uid', $str, '$'));
    }

    function &uidContains($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('view_uid', $str));
    }

    function &uidIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('view_uid', $values));
    }

    function &uidNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('view_uid', $values));
    }

    function &lastIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('view_last', $value));
    }

    function &lastIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('view_last', $value, '>'));
    }

    function &lastIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('view_last', $value, '<'));
    }

    function &lastIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('view_last', $value, '>='));
    }

    function &lastIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('view_last', $value, '<='));
    }

    function &lastIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('view_last', $values));
    }

    function &lastNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('view_last', $values));
    }

    function &node_idIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('view_node_id', $value));
    }

    function &node_idIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('view_node_id', $value, '>'));
    }

    function &node_idIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('view_node_id', $value, '<'));
    }

    function &node_idIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('view_node_id', $value, '>='));
    }

    function &node_idIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('view_node_id', $value, '<='));
    }

    function &node_idIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('view_node_id', $values));
    }

    function &node_idNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('view_node_id', $values));
    }
}