<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
Xigg/library/Xigg/Model/VoteCriteria.php
*/
require_once 'Sabai/Model/EntityCriteria.php';

class Xigg_Model_VoteCriteriaBase extends Sabai_Model_EntityCriteria
{

    function &idIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('vote_id', $value));
    }

    function &idIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('vote_id', $value, '>'));
    }

    function &idIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('vote_id', $value, '<'));
    }

    function &idIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('vote_id', $value, '>='));
    }

    function &idIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('vote_id', $value, '<='));
    }

    function &idIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('vote_id', $values));
    }

    function &idNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('vote_id', $values));
    }

    function &createdIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('vote_created', $value));
    }

    function &createdIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('vote_created', $value, '>'));
    }

    function &createdIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('vote_created', $value, '<'));
    }

    function &createdIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('vote_created', $value, '>='));
    }

    function &createdIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('vote_created', $value, '<='));
    }

    function &createdIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('vote_created', $values));
    }

    function &createdNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('vote_created', $values));
    }

    function &updatedIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('vote_updated', $value));
    }

    function &updatedIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('vote_updated', $value, '>'));
    }

    function &updatedIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('vote_updated', $value, '<'));
    }

    function &updatedIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('vote_updated', $value, '>='));
    }

    function &updatedIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('vote_updated', $value, '<='));
    }

    function &updatedIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('vote_updated', $values));
    }

    function &updatedNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('vote_updated', $values));
    }

    function &scoreIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('vote_score', $value));
    }

    function &scoreIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('vote_score', $value, '>'));
    }

    function &scoreIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('vote_score', $value, '<'));
    }

    function &scoreIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('vote_score', $value, '>='));
    }

    function &scoreIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('vote_score', $value, '<='));
    }

    function &scoreIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('vote_score', $values));
    }

    function &scoreNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('vote_score', $values));
    }

    function &ipIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('vote_ip', $value));
    }

    function &ipStartsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('vote_ip', $str, '^'));
    }

    function &ipEndsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('vote_ip', $str, '$'));
    }

    function &ipContains($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('vote_ip', $str));
    }

    function &ipIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('vote_ip', $values));
    }

    function &ipNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('vote_ip', $values));
    }

    function &node_idIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('vote_node_id', $value));
    }

    function &node_idIsGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('vote_node_id', $value, '>'));
    }

    function &node_idIsSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('vote_node_id', $value, '<'));
    }

    function &node_idIsOrGreaterThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('vote_node_id', $value, '>='));
    }

    function &node_idIsOrSmallerThan($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('vote_node_id', $value, '<='));
    }

    function &node_idIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('vote_node_id', $values));
    }

    function &node_idNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('vote_node_id', $values));
    }

    function &useridIs($value)
    {
        return $this->add(Sabai_Model_Criteria::createValue('vote_userid', $value));
    }

    function &useridStartsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('vote_userid', $str, '^'));
    }

    function &useridEndsWith($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('vote_userid', $str, '$'));
    }

    function &useridContains($str)
    {
        return $this->add(Sabai_Model_Criteria::createString('vote_userid', $str));
    }

    function &useridIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createIn('vote_userid', $values));
    }

    function &useridNotIn($values)
    {
        return $this->add(Sabai_Model_Criteria::createNotIn('vote_userid', $values));
    }
}