<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
*/

require_once 'Sabai/Model/EntityCollection/Decorator/User.php';

class Xigg_Model_VotesWithUserBase extends Sabai_Model_EntityCollection_Decorator_User
{
    function Xigg_Model_VotesWithUserBase(&$collection)
    {
        parent::Sabai_Model_EntityCollection_Decorator_User($collection);
    }
}