<?php
/*
This file has been generated by the Sabai scaffold script. Do not edit this file directly.
If you need to customize the class, use the following file:
Xigg/library/Xigg/Model/VoteForm.php
*/
class Xigg_Model_VoteFormBase extends Sabai_Model_EntityForm
{
    function onInit($params)
    {
        require_once 'Sabai/Form/Element/InputText.php';
        $this->addElement(new Sabai_Form_Element_InputText('score', 5, 255), _('Score'));
        require_once 'Sabai/Form/Element/Text.php';
        $this->addElement(new Sabai_Form_Element_Text('ip'), _('Ip'));
        require_once 'Sabai/Form/Element/SelectEntity.php';
        $element =& new Sabai_Form_Element_SelectEntity($this->_model, 'Node', 'Node', 1);
        $this->addElement($element, _('node'));
        require_once 'Sabai/Form/Element/InputText.php';
        $this->addElement(new Sabai_Form_Element_InputText('userid', 30, 255), _('User ID'));
        $this->_onInit($params);
    }

    function onEntity(&$entity)
    {
        if ($this->hasElement('score')) {
            $this->setValueFor('score', $entity->getVar('score'));
        }
        if ($this->hasElement('ip')) {
            $this->setValueFor('ip', $entity->getVar('ip'));
        }
        if ($this->hasElement('Node')) {
            $this->setValueFor('Node', $entity->getVar('node_id'));
        }
        if ($this->hasElement('userid')) {
            $this->setValueFor('userid', $entity->getVar('userid'));
        }
        $this->_onEntity($entity);
    }

    function onFillEntity(&$entity)
    {
        $vars = array();
        foreach (array('score' => 'score', 'ip' => 'ip', 'node_id' => 'Node', 'userid' => 'userid') as $var_name => $form_name) {
            if ($this->hasElement($form_name)) {
                $vars[$var_name] = $this->getValueFor($form_name);
            }
        }
        $entity->setVars($vars);
        $this->_onFillEntity($entity);
    }

    function _onInit($params){}
    function _onEntity(&$entity){}
    function _onFillEntity(&$entity){}
}